databases:
  - name: Spardha
    plan: free
    databaseName: Spardha
    user: Spardha

services:
  - type: web
    plan: free
    name: Spardha
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Spardha.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spardhadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4